# Generated by Django 4.0.7 on 2022-09-29 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_owner_board_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ('-modify_dt',), 'verbose_name': '커뮤니티 게시판', 'verbose_name_plural': '커뮤니티 게시판'},
        ),
    ]
