# Generated by Django 4.0.7 on 2022-09-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
