# Generated by Django 4.0.7 on 2022-09-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-modify_dt',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterModelTable(
            name='post',
            table='blog_posts',
        ),
    ]
